dist: trusty
sudo: required
language: node_js
node_js:
- '7'
services:
  - docker
script:
  - npm run webpack
branches:
  only:
  - master
  - development
deploy:
  - provider: script
    script: deploy.sh
    skip_cleanup: true
    on:
      branch: development
  - provider: script
    script: deploy.sh prod
    skip_cleanup: true
    on:
      branch: master

