dist: trusty
sudo: required
language: node_js
node_js:
- '7'
services:
  - docker
before_script:
  - npm run webpack
script:
  - docker login --username=_ --password=$(echo $API_KEY) registry.heroku.com
  - docker build -t registry.heroku.com/vstaem-dev/web .
branches:
  only:
  - master
  - development
deploy:
  - provider: script
    script: deploy.sh
    on:
      branch: development
  - provider: script
    script: deploy.sh prod
    on:
      branch: master

