dist: trusty
sudo: required
language: node_js
node_js:
- '7'
services:
  - docker
install: true
before_script:
  - npm run webpack
script:
  - docker login --username=_ --password=$(echo $API_KEY) registry.heroku.com
  - docker build -t registry.heroku.com/vstaem-dev/web .
  - docker push registry.heroku.com/vstaem-dev/web
branches:
  only:
  - master
  - development
deploy:
  provider: heroku
  app:
    master: vstaem
    development: vstaem-dev
  api_key:
    master:
      secure: MW5xk9USNn/tzP1dTPNeAOTFNOFLMAWWsRC0TULBVylpOa9HtyuQTZy98MRLpfSmBFqXTj51cMi3BaYlsI7L0BEk+99GHEti5xVs/ym6/FHjuT1fKfJi0zOfTpaJWUJvaUsZJWkxlGevaOUS31VOJYPGSq5SoYCd3WxJxvNT5rEnt7jpCioflTSNUmgEZxW5IuT7bBs/D6Pe4W/+eeZ7sV0IrCgNF8Za4tZSmWQDyJUAR0uje23i/Po7mOeL5ows8xenGnKUKlcc8iVGvseVa+QYQsd3RtD7d4oQpi0kkVoU3FsvahH4G0t2FvaiTgVNNfntrr7Tv5276udCztTdfixB7yCiArMAWMfvYplYB2EPzPHGjvakbnQzjflwWCLoarcq+38jkZ7BTe+zQNdR+sq2g1p6H4AKv4ABNy7DdrMP/q71eoBW54gYNYT4BjL9CdYRyVsNnwJaE47PRTNMlQuMzfCGaxPiRak5Csa06diEOtlFYjmB0z5T4yGk/1r6g48tuI1dQIkKhsn5ncfJVw53Owd2/URGHw5NNafTmyyyGJ2KaLT9rL2X4DBY3LxFuin1kHLQ+i23CnPjaGePFyBADfOhMzpUBid20jE7edXXjiOJ1SPxF6IG9av/480+prmgkM2myOkLB3i/08aqpia1uNxOzmsDNrO+EFDlGjk=
    development:
      secure: cpTFuqHCm86fF2GJfCZTQoYIV/Mwt21M4aXoG/NW9bAjaYWLGj+ilkX2MTje0q5lIJWRbpOkpXMo+gcBaSOd5gkUKdIM10qprgE2cRYGbBSR7JqJwBE4IYqo8P7V5a8aiwFy1CzcJz2zDHVeCR7QP0HMqlLJAwjCCLqIcG5ANmlcyTC51E8QRePTWD2F0+0Xt6AXQLWqp2XUmq8K/TGVafa0gjPkMkZ3E7yh1ckzY6pkch4S+6UM8lqcRsmxhU6Ziz8nFHOAdHqXyLdhWGAntNnEctaY4GleWCDDvIPjI5zOWkUZQMhRwQPcn6xZxrZ8FKWMz3NhNnQzcjhywzdxIkpSwaIUi6MEVavd7Hiu/kQ3pSX3Hn5s0ejxsGTCUHgwdDV1VODVvyjLHFYXVg+L1/EEOJvFxAt8Of1A1uGlOHcwvrHWpTE4l1shd4Y/ewLRrE3e2IZdO3GifZiNUsp95vadNtiJNSewOR+qPBa69rGtS8Kqs9Dxcx537DOIM67ZjxXlcBe7bSThpmy8r09nCxiX9ZNQUONPe9hDKoCYcZTBZRxpi/Q/MjCWc8KZC4AfxnldrsWaTDx284oWRZHh7ElWeT/s6HH8BjKzCJa/L6Kfsv8tJ11Kic234pz9OqT1SVVTZYijQENGXF8IbcgGwImoZEvQiLJOCSa/0dVK9vw=
